### PR TITLE
Adding Various Functions

### PR DESCRIPTION
**Pull request by nickginsberg**
Adding functions for:

- Front fill
- Fill NA
- Rename cols
- Random sampling

Also updating docs to latest.

### CODE REVIEW

**Comment by nickslevine** [comment]
This looks great Nick, thanks! Is it worth adding the ability in `fFill` and `fillNA` to only apply the operation to a subset of columns - as in `parseNums`?

**Comment by nickginsberg** [comment]
Definitely not a bad idea! Will add

**Comment by nickginsberg** [comment]
Updated to include a cols field!

It seems curry doesn't like when you use default params (I was going to set to [] by default), so I just made it so passing either [] or null will do all cols.

**Comment by nickslevine** [comment]
Sounds good! Thanks. Merged.

**Comment by nickslevine** [comment]
@nickginsberg just published 0.0.20 on npm with your additions: https://www.npmjs.com/package/zebras

**Pull request merged**
