### PR TITLE
Port docs from README into JSDoc

### PR DESCRIPTION
**Pull request by amytych**
This has an advantage of keeping documentation close to code making it much easier to update when the code is modified. And the docs can be automatically generated into a searchable website.

Template can be further tweaked, but this one should serve as a good starting point.

These docs are also more detailed than the README version, each method describes its params, return values and has an example. I definitely need you to check this, I had to make some judgment calls on explaining params and returns, and also when providing examples for methods that were missing those in README.

You can preview docs here: https://amytych.github.io/zebras/Z.html

Please point out any fixes/improvements I should add so we can merge and publish. ✌️

PS. Most of the files in this PR are from JSDoc generated website and can be ignored, the only file of interest really is `zebras.js` and I also removed Documentation section in README (replaced with the link to the new docs)

### CODE REVIEW

**Comment by nickslevine** [comment]
This looks awesome. Will have a read through today and then merge.

**Comment by nickslevine** [comment]
Thanks for doing this! It looks great. Just had a read through. A few tiny things I noticed:
- In the addCol example, the function called should be Z.addCol() rather than Z.valueCounts(). 
- The groupBy function examples could use the "Z." prefix; right now they're listed as if they've been imported directly into the project. 
- For the getCol example, the first argument should be "value" rather than "label." 

Do those make sense? 

Another thought, and this could be done at a later date, was whether it would be useful to group functions by category in the docs, as is done, eg, in the [Lodash docs](https://lodash.com/docs/4.17.11). 

Also I bought a zebras domain in case we want to give the docs a non-github URL. 🤘

**Comment by amytych** [comment]
I fixed the issues you spotted. I also added a @category tag to the methods, good if you double check I didn't mix anything up. Later on we can look into customising the template to group the functions together in the sidebar.

> Also I bought a zebras domain in case we want to give the docs a non-github URL. 🤘
That sounds great! 💯

**Comment by nickslevine** [comment]
Great thanks! Just merged.

**Comment by amytych** [comment]
Cool! Be sure to [publish them](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)! You can also hook up the domain while you're at it, if you want to :-)

**Pull request merged**
